/* eslint-disable */
// Auto-generated by scripts/index-content.ts — do not edit by hand.
export const CONTENT_INDEX = {
  "generatedAt": "2026-04-23T06:00:31.794Z",
  "itemCount": 31,
  "moduleCount": 6,
  "itemIds": [
    "nom-gb-t1-01",
    "nom-gb-t1-02",
    "nom-gb-t1-03",
    "nom-gb-t1-04",
    "nom-gb-t2-01",
    "nom-gb-t2-02",
    "nom-gb-t3-01",
    "nom-cp-t1-01",
    "nom-cp-t1-02",
    "nom-cp-t1-03",
    "nom-cp-t2-01",
    "nom-cp-t2-02",
    "nom-cp-t3-01",
    "vb-gov-t1-01",
    "vb-gov-t1-02",
    "vb-gov-t2-01",
    "vb-gov-t3-01",
    "syn-v2-t1-01",
    "syn-v2-t1-02",
    "syn-v2-t1-03",
    "syn-v2-t2-01",
    "syn-v2-t2-02",
    "syn-v2-t3-01",
    "flow-con-t1-01",
    "flow-con-t1-02",
    "flow-con-t2-01",
    "flow-con-t3-01",
    "perf-ec-t1-01",
    "perf-ec-t1-02",
    "perf-ec-t2-01",
    "perf-ec-t3-01"
  ],
  "moduleSlugs": [
    "gender-bundle",
    "case-picker",
    "verb-government",
    "v2-slot-machine",
    "connectors",
    "error-clinic"
  ]
} as const;
