// Auto-generated by scripts/generate-content-manifest.ts — do not edit by hand.
// Client-safe metadata about content modules. Contains no exercise items.

export type ContentModuleMeta = {
  id: string;
  slug: string;
  systemId: string;
  title: string;
  description: string;
  idPrefix: string;
  tierCounts: [number, number, number];
  totalCount: number;
};

export const CONTENT_MODULE_META: ContentModuleMeta[] = [
  {
    id: "gender-bundle",
    slug: "gender-bundle",
    systemId: "nominal",
    title: "Gender Gym",
    description:
      "Master der/die/das with articles, noun-in-context cloze, and recognition drills.",
    idPrefix: "nom-gb",
    tierCounts: [1445, 1974, 10081],
    totalCount: 13500,
  },
  {
    id: "pronouns",
    slug: "pronouns",
    systemId: "nominal",
    title: "Pronouns by Case",
    description:
      "Fill in the correct pronoun (ich/mich/mir, du/dich/dir, er/ihn/ihm…) in real sentences.",
    idPrefix: "nom-pro",
    tierCounts: [324, 278, 1372],
    totalCount: 1974,
  },
  {
    id: "reflexives",
    slug: "reflexives",
    systemId: "verb",
    title: "Reflexive Verbs",
    description:
      "Choose the correct reflexive pronoun (mich/dich/sich/uns/euch) in context.",
    idPrefix: "vb-ref",
    tierCounts: [36, 34, 104],
    totalCount: 174,
  },
  {
    id: "konjunktiv-ii",
    slug: "konjunktiv-ii",
    systemId: "verb",
    title: "Konjunktiv II",
    description:
      "Form hypotheticals, wishes, and polite requests with wäre, hätte, würde, and modal stems.",
    idPrefix: "vb-kii",
    tierCounts: [8, 8, 8],
    totalCount: 24,
  },
  {
    id: "passiv",
    slug: "passiv",
    systemId: "verb",
    title: "Passiv",
    description:
      "Build passive-voice sentences with werden + Partizip II across Präsens, Präteritum, and Perfekt.",
    idPrefix: "vb-pas",
    tierCounts: [7, 7, 6],
    totalCount: 20,
  },
  {
    id: "valency",
    slug: "valency",
    systemId: "verb",
    title: "Verb Valency",
    description:
      "Learn which case each verb governs — fixed-dative verbs, two-object verbs, and fixed prepositions.",
    idPrefix: "vb-val",
    tierCounts: [7, 7, 6],
    totalCount: 20,
  },
  {
    id: "adjective-endings",
    slug: "adjective-endings",
    systemId: "nominal",
    title: "Adjective Endings",
    description:
      "Choose the right adjective ending after der-words, ein-words, and no article at all.",
    idPrefix: "nm-adj",
    tierCounts: [8, 7, 6],
    totalCount: 21,
  },
  {
    id: "two-way-prepositions",
    slug: "two-way-prepositions",
    systemId: "nominal",
    title: "Two-Way Prepositions",
    description:
      "Accusative for motion, dative for location — plus fixed-case idioms and contractions.",
    idPrefix: "nm-2wp",
    tierCounts: [8, 8, 6],
    totalCount: 22,
  },
  {
    id: "n-deklination",
    slug: "n-deklination",
    systemId: "nominal",
    title: "n-Deklination",
    description:
      "Weak masculine nouns (Junge, Kollege, Student, Name…) that add -n/-en outside the nominative.",
    idPrefix: "nm-nde",
    tierCounts: [7, 7, 6],
    totalCount: 20,
  },
  {
    id: "relative-clauses",
    slug: "relative-clauses",
    systemId: "syntax",
    title: "Relative Clauses",
    description:
      "Pick the relative pronoun whose gender matches its noun and whose case matches its role.",
    idPrefix: "sx-rel",
    tierCounts: [7, 7, 7],
    totalCount: 21,
  },
  {
    id: "sentence-builder",
    slug: "sentence-builder",
    systemId: "syntax",
    title: "Sentence Builder",
    description:
      "Reconstruct German sentences by putting shuffled words in the correct order.",
    idPrefix: "syn-sb",
    tierCounts: [1479, 1490, 6984],
    totalCount: 9953,
  },
  {
    id: "negation-lab",
    slug: "negation-lab",
    systemId: "syntax",
    title: "Negation Lab",
    description:
      "Fill in nicht/kein and fix common negation errors in real sentences.",
    idPrefix: "syn-neg",
    tierCounts: [326, 296, 1318],
    totalCount: 1940,
  },
  {
    id: "connectors",
    slug: "connectors",
    systemId: "flow",
    title: "Connector Mastery",
    description:
      "Fill in subordinating and coordinating connectors (weil, obwohl, deshalb…) in context.",
    idPrefix: "flow-con",
    tierCounts: [188, 174, 1355],
    totalCount: 1717,
  },
  {
    id: "core-vocab",
    slug: "core-vocab",
    systemId: "vocab",
    title: "Core Vocabulary",
    description:
      "Two-direction meaning drills (DE→EN and EN→DE) for high-frequency German words.",
    idPrefix: "voc-cv",
    tierCounts: [2642, 2911, 13456],
    totalCount: 19009,
  },
  {
    id: "sentence-cloze",
    slug: "sentence-cloze",
    systemId: "vocab",
    title: "Sentence Cloze",
    description:
      "Recall vocabulary in context: fill in the missing word in authentic sentences.",
    idPrefix: "voc-sc",
    tierCounts: [1221, 1377, 6261],
    totalCount: 8859,
  },
  {
    id: "error-clinic",
    slug: "error-clinic",
    systemId: "performance",
    title: "Error Clinic",
    description:
      "Spot and fix pronoun-case, word-order, connector, and negation errors.",
    idPrefix: "perf-ec",
    tierCounts: [164, 156, 724],
    totalCount: 1044,
  },
];
