/* eslint-disable */
// Auto-generated by scripts/generate-content.ts — do not edit by hand.
import type { ExerciseItem } from "@/lib/content/schema";

export const reflexivesTier2: ExerciseItem[] = [
  {
    id: "vb-ref-t2-001",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Du möchtest ____ nicht einmal verabschieden.",
    options: ["euch", "sich", "mich", "dich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3383524461",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-002",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Die Umstände haben ____ geändert.",
    options: ["dich", "euch", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2248742837",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-003",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Hier kann man ____ nirgendwo hinsetzen.",
    options: ["mich", "sich", "dich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2263058465",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-004",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Jane verspätete ____ aufgrund des Sturms.",
    options: ["sich", "dich", "mich", "uns"],
    answer: 0,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3868667236",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-005",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Die Situation hat ____ dramatisch geändert.",
    options: ["mich", "sich", "dich", "uns"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2426254916",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-006",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Entspannen Sie ____, ich könnte niemals so grausam sein.",
    options: ["euch", "sich", "mich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1523403751",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-007",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich möchte ____ keinen Ärger bereiten.",
    options: ["sich", "mich", "dich", "euch"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:389551309",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-008",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich muss ____ um mein Vieh kümmern.",
    options: ["sich", "uns", "mich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:663326337",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-009",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich war schüchtern und habe ____ mit keinem einzigen Deutschen angefreundet.",
    options: ["sich", "uns", "mich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:141354208",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-010",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "In diesem Punkt könnte ich ____ vielleicht irren.",
    options: ["sich", "mich", "dich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:622776277",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-011",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich muss ____ dafür bedanken.",
    options: ["mich", "dich", "sich", "uns"],
    answer: 0,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:109907923",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-012",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Aber ich möchte ____ mit ihm befreunden.",
    options: ["dich", "euch", "mich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1870754201",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-013",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ mies wegen gestern.",
    options: ["uns", "mich", "sich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1117362521",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-014",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich möchte ____ nicht in dich verlieben.",
    options: ["euch", "uns", "dich", "mich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4060216802",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-015",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich habe einen Kater und erinnere ____ nicht mehr an die Party.",
    options: ["euch", "uns", "mich", "dich"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1504981420",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-016",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Derzeit beteiligen ____ insgesamt Länder.",
    options: ["mich", "dich", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:554587729",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-017",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Sein Schwiegersohn hat ____ vollständig von seiner Krankheit erholt.",
    options: ["mich", "euch", "dich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1014212985",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-018",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Versuch nicht, ____ zu ärgern!",
    options: ["euch", "dich", "sich", "mich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:859735456",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-019",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es fühlt ____ mehr wie ein Akt der Verzweiflung an.",
    options: ["mich", "sich", "uns", "dich"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2530119885",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-020",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fürchte, sie könnte ____ verlaufen haben.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:210847053",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-021",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es würde ____ nicht wundern.",
    options: ["euch", "mich", "sich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:540182711",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-022",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Und er sagt, wir verhalten ____ eigenartig.",
    options: ["mich", "dich", "uns", "euch"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2837454924",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-023",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Setz ____ in die Karre.",
    options: ["euch", "uns", "dich", "mich"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3851441385",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-024",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich fühle ____ nicht mehr sehr britisch, sondern immer schottischer.",
    options: ["mich", "dich", "uns", "euch"],
    answer: 0,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4273182439",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-025",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Du willst ____ doch nicht verirren.",
    options: ["uns", "euch", "mich", "dich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3981544034",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-026",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Na ja, ich kann ____ nicht beschweren.",
    options: ["mich", "sich", "uns", "dich"],
    answer: 0,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3592335524",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-027",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Dein Freund informiert ____ über die Einzelheiten.",
    options: ["euch", "uns", "dich", "sich"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3275988257",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-028",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühlte ____ so leicht wie eine Feder.",
    options: ["uns", "mich", "dich", "sich"],
    answer: 1,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2214796466",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-029",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Gerade hat ____ der Vorhang bewegt.",
    options: ["mich", "euch", "dich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1538441509",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-030",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Er hatte vier Stunden, um ____ zu erholen.",
    options: ["mich", "dich", "euch", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1114597938",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-031",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Der Mann hat ____ im Wald verlaufen.",
    options: ["uns", "euch", "dich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3641155522",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-032",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie informierte ____ über ihre Abreise.",
    options: ["mich", "dich", "euch", "sich"],
    answer: 0,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3142748389",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-033",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich befürchte, dass ich ____ dort langweile.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 3,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3528572135",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t2-034",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Deine Entschuldigungen sind für ____ wertlos.",
    options: ["dich", "sich", "mich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 2,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1867263132",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
];
