/* eslint-disable */
// Auto-generated by scripts/generate-content.ts — do not edit by hand.
import type { ExerciseItem } from "@/lib/content/schema";

export const reflexivesTier3: ExerciseItem[] = [
  {
    id: "vb-ref-t3-001",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ist es denn so entsetzlich für Sie, dass ____ jemand um Sie sorgt?",
    options: ["mich", "dich", "sich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:401449774",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-002",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ein wahrer Freund würde ____ beraten.",
    options: ["uns", "euch", "mich", "dich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3388145117",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-003",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich habe die Tomaten für ____ gewaschen.",
    options: ["dich", "mich", "euch", "uns"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2477020210",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-004",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es gibt ein ganzes Lagerhaus, in dem ____ nur Gemälde befinden.",
    options: ["sich", "uns", "euch", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:99212989",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-005",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich erinnere ____, dass ich einen begrenzten Vorrat hatte.",
    options: ["uns", "mich", "sich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3795490184",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-006",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich will das Massaker rächen, aber ich erinnere ____ auch daran und habe Angst.",
    options: ["dich", "euch", "uns", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1386370978",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-007",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Dann werde ich ____ bei der Station absetzen.",
    options: ["dich", "sich", "euch", "uns"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3629430968",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-008",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir treffen ____ mittags in der Klinik.",
    options: ["sich", "mich", "uns", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3818818580",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-009",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich trug einen Mantel, um ____ nicht zu erkälten.",
    options: ["euch", "mich", "uns", "dich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:11457376",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-010",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir haben einen Grund ____ zu verspäten.",
    options: ["dich", "mich", "euch", "uns"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2601235190",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-011",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wenn du vorsprechen willst, setz ____ hin.",
    options: ["dich", "mich", "sich", "uns"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3991005239",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-012",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es wird ____ nur kurz komisch anfühlen.",
    options: ["uns", "mich", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2875841605",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-013",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Du darfst ____ nicht zu sehr auf die äußere Erscheinung verlassen.",
    options: ["uns", "dich", "sich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:511628293",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-014",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Der Unteroffizier kümmert ____ um Sie.",
    options: ["sich", "mich", "dich", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2491600956",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-015",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Rezeption und Lobby befinden ____ im Hauptgebäude.",
    options: ["mich", "uns", "euch", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:268744090",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-016",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es würde ____ nur verwirren.",
    options: ["sich", "uns", "euch", "dich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4180799874",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-017",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Janes Büro befindet ____ zwei Meilen westlich von ihrem Haus.",
    options: ["uns", "euch", "dich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2693939690",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-018",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich wachte auf und fühlte ____ wieder total schwindlig.",
    options: ["uns", "euch", "mich", "dich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3727278176",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-019",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ durchaus imstande, das Kind alleine aufzuziehen.",
    options: ["euch", "sich", "mich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1390777151",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-020",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Dieser Söldner interessiert ____ nur für Geld.",
    options: ["mich", "euch", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2575000622",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-021",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Man sollte ____ seine Freunde sehr sorgfältig auswählen.",
    options: ["sich", "uns", "euch", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2978395988",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-022",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Gleichfalls müssen wir klarmachen, dass die Europäische Union ____ verändern muss.",
    options: ["sich", "uns", "euch", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2404989129",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-023",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich dachte, die Rückkehr deiner Tochter würde ____ erfreuen.",
    options: ["euch", "sich", "dich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2530069768",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-024",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Diejenigen, die ____ widersetzen wollen, müssen zusammenarbeiten.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:896028017",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-025",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Setzen Sie ____ hin, bevor Sie umfallen.",
    options: ["mich", "sich", "dich", "uns"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2693990270",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-026",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Man kann ____ entweder anmelden oder als Gast abstimmen.",
    options: ["dich", "sich", "uns", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3495527297",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-027",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Jetzt entschuldige ____, ich muss jemanden abhören.",
    options: ["mich", "uns", "sich", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:153655164",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-028",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Eines wird ____ nicht ändern: unser Engagement unseren Kunden gegenüber.",
    options: ["sich", "euch", "dich", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1540002513",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-029",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Wir werden ____ diesem antidemokratischen Manöver kompromisslos widersetzen.",
    options: ["uns", "euch", "dich", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:43505291",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-030",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Mit dem Helm fühlte ich ____ unbesiegbar.",
    options: ["dich", "euch", "mich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:794777272",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-031",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie verdienten ____ Respekt und Bewunderung.",
    options: ["sich", "dich", "mich", "uns"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2051719516",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-032",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir haben ____ beeilt wegen der Ausgangssperre.",
    options: ["uns", "sich", "dich", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2261120733",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-033",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Liebe Mitbürger, wir befinden ____ im Krieg.",
    options: ["euch", "dich", "mich", "uns"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2754599739",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-034",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Er erinnerte ____ an ihre Haare und ihre lackierten Fingernägel.",
    options: ["mich", "uns", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:191922615",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-035",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Aber nun bist du Single und fühlst ____ miserabel, weil du glaubst, es ist",
    options: ["euch", "dich", "uns", "mich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:717982617",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-036",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Du fängst an ____ zu irritieren.",
    options: ["mich", "euch", "uns", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3336494676",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-037",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ungewöhnlich, aber es breitet ____ sehr schnell aus.",
    options: ["sich", "mich", "dich", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3802439921",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-038",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Es gibt ein Kopfgeld auf ____, mein Freund.",
    options: ["uns", "dich", "sich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3459459050",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-039",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Nun, Sie können ____ vorstellen, es war mein Ruin.",
    options: ["dich", "mich", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2919503821",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-040",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich würde ____ grässlich fühlen.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2997852216",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-041",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Die Eisenbahnstrecke befindet ____ nun im Aufbau.",
    options: ["sich", "uns", "dich", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1551558060",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-042",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich bin intellektuell neugierig, aber meine Meinung hat ____ nicht geändert.",
    options: ["sich", "mich", "uns", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:640317047",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-043",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühlte ____ so geehrt, dabei zu sein.",
    options: ["mich", "euch", "dich", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2698409481",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-044",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Mit dir an meiner Seite fühle ich ____ unschlagbar.",
    options: ["euch", "mich", "uns", "sich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3247684063",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-045",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Er verliebte ____ augenblicklich in sie.",
    options: ["sich", "mich", "euch", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3489571466",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-046",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Du musst ____ nächstes Semester bewerben.",
    options: ["dich", "uns", "mich", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4225367012",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-047",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Halt ____ am Geländer fest.",
    options: ["euch", "dich", "sich", "mich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:589487543",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-048",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Setz ____ da vorn hin, ich werde sie runterholen.",
    options: ["mich", "sich", "euch", "dich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:320949756",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-049",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ so leicht und erhaben.",
    options: ["uns", "sich", "euch", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2851558498",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-050",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ihre freundlichen Worte werden ____ motivieren.",
    options: ["mich", "uns", "dich", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:482675277",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-051",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Seine Brüder interessieren ____ nur für Pferderennen.",
    options: ["uns", "dich", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1441122460",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-052",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wieso fühlst du ____ so panisch?",
    options: ["mich", "sich", "dich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3624756093",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-053",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich habe Freunde, die ____ da auskennen.",
    options: ["euch", "uns", "mich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4019354482",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-054",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Warum sollte unser Volk ____ solchem Verhalten hingeben?",
    options: ["uns", "sich", "dich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3102969491",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-055",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Morgen werde ich aufwachen und ____ hoffnungsvoll fühlen.",
    options: ["euch", "sich", "uns", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:841075566",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-056",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich habe es in einem Schaufenster gesehen und ____ darin verliebt.",
    options: ["dich", "uns", "euch", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1452882033",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-057",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Meine Mitfahrgelegenheit hat ____ an der Kreuzung abgesetzt.",
    options: ["sich", "euch", "uns", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2611802227",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-058",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie setzt ____ aufs Pferd und husch!",
    options: ["uns", "euch", "dich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2347255804",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-059",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Treffen wir ____ also im Foyer des Hotels.",
    options: ["uns", "sich", "euch", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2869811538",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-060",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wo befindet ____ das nächste Reisebüro?",
    options: ["euch", "dich", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:547254994",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-061",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich interessiere ____ für Fotografie.",
    options: ["sich", "uns", "mich", "dich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1455100684",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-062",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Der Rest davon befindet ____ in der Mappe.",
    options: ["sich", "uns", "euch", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3224738865",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-063",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich werde ____ mit dem Innenminister treffen.",
    options: ["mich", "sich", "uns", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1481679014",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-064",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich darf sagen, es freut ____, Sie wieder hier zu erblicken, Sir.",
    options: ["euch", "mich", "uns", "sich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3183227682",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-065",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Wir freuen ____, für die Weihnachtszeit ein weiteres Konzert bestätigen zu",
    options: ["euch", "uns", "mich", "sich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1804929705",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-066",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Astronomie interessiert ____ nicht sehr.",
    options: ["mich", "sich", "euch", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1054578052",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-067",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich fühle ____ wie ein Kind bei seiner eigenen Überraschungsparty.",
    options: ["mich", "euch", "uns", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2543801824",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-068",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Vorerst möchte ich ____ hierauf konzentrieren.",
    options: ["sich", "mich", "dich", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1204260700",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-069",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Und deine Freunde halten ____ für geistreich.",
    options: ["euch", "mich", "sich", "dich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:101789933",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-070",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wenn Sie ____ entschuldigen, ich muss die Wache postieren.",
    options: ["mich", "euch", "uns", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3688783361",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-071",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Die vorliegenden Änderungsanträge lassen ____, grob gesprochen, in drei",
    options: ["uns", "euch", "mich", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1143263750",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-072",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Mittlerweile interessieren ____ zunehmend mehr Männer für die",
    options: ["uns", "dich", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1090458707",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-073",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Körperlich fühle ich ____, als könnte ich einen Panzer demolieren.",
    options: ["mich", "dich", "euch", "sich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:258394258",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-074",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Aber wie konnten Sie ____ überholen?",
    options: ["dich", "uns", "sich", "mich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:888992172",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-075",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich entschuldige ____ für meinen plötzlichen Aufbruch.",
    options: ["uns", "euch", "sich", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1928077002",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-076",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "In diesem Atom befindet ____ ein Proton.",
    options: ["mich", "dich", "euch", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:176333340",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-077",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Dann lassen Sie ____ Ihre Erinnerung auffrischen.",
    options: ["mich", "uns", "euch", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3476535307",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-078",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Die beiden Übergangsbogen krümmen ____ in entgegengesetzte Richtungen.",
    options: ["mich", "euch", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:507662475",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-079",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich erinnere ____ auch an das Hundegebell.",
    options: ["sich", "dich", "mich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1668303703",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-080",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Er kann glitzern und leuchten, er kann ____ bewegen und Geräusche machen.",
    options: ["uns", "sich", "mich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:141466502",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-081",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Es ist bewegend zu sehen, wie ____ eine große Familie im Unglück vereint.",
    options: ["euch", "sich", "mich", "uns"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:919125685",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-082",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Du kannst ____ deiner neuen Gouvernante vorstellen.",
    options: ["uns", "sich", "mich", "dich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3724956534",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-083",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Die Geschichte ist mit Fällen übersät, in denen ____ alle geirrt haben.",
    options: ["sich", "mich", "uns", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4151822446",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-084",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich glaube, ich war es leid, ____ zu fühlen, als würde ich nicht dazugehören.",
    options: ["euch", "mich", "dich", "uns"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3759258859",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-085",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Außerdem sollten wir ____ darum kümmern, wie wir in Europa Investitionen",
    options: ["sich", "dich", "uns", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:642551962",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-086",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "An mein damaliges Leben erinnere ich ____ nicht sehr gut.",
    options: ["mich", "uns", "dich", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:403641377",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-087",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich kann fühlen, wie ____ meine Poren festigen.",
    options: ["euch", "sich", "mich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:937379465",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-088",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Warum sollte ____ dein Nerz interessieren?",
    options: ["sich", "dich", "mich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:356355601",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-089",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Wo ist dieses utopische Wunderland, das sie ____ versprochen hat?",
    options: ["mich", "euch", "uns", "dich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3016310184",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-090",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ wie Kind am Weihnachtstag.",
    options: ["mich", "sich", "uns", "euch"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:91772844",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-091",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Das traditionsreiche Hotel-Restaurant befindet ____ am westlichen Stadtrand",
    options: ["mich", "dich", "sich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3024694833",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-092",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich denke gern daran zurück, wie freundschaftlich ____ unsere Wege trennten.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3289511560",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-093",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Mama, es ist dein Bad, du musst ____ wohlfühlen.",
    options: ["mich", "uns", "sich", "dich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1497601348",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-094",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich fühlte ____ ruhelos und führungslos und ich dachte, die Schule würde mir",
    options: ["dich", "mich", "sich", "uns"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1626920293",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-095",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ gerade nicht sehr gastfreundlich.",
    options: ["uns", "mich", "sich", "dich"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3591917980",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-096",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie interessieren ____ für den Beruf der Kosmetikerin.",
    options: ["uns", "dich", "sich", "mich"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2243062014",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-097",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Er setzte ____ auf einen Kirchturm, als wäre es ein Thron.",
    options: ["mich", "uns", "euch", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2604650579",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-098",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Hunde altern siebenmal schneller und beschweren ____ nicht.",
    options: ["sich", "euch", "uns", "dich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3086567773",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-099",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir versuchen, ____ an das indianische Essen zu gewöhnen.",
    options: ["uns", "sich", "euch", "mich"],
    answer: 0,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1771332263",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-100",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Das Observatorium und Planetarium befinden ____ im Südteil der Stadt.",
    options: ["euch", "dich", "uns", "sich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2711680662",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-101",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich werde gehen und gucken, ob ich ____ mit den Kühen anfreunden kann.",
    options: ["dich", "uns", "euch", "mich"],
    answer: 3,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2123496844",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-102",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Erinnerst du ____, eine weiße Tulpe bekommen zu haben?",
    options: ["uns", "sich", "dich", "euch"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1026485738",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-103",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich meine, erinnere ____ daran, als du dein Baby nicht anlächeln wolltest, weil",
    options: ["mich", "dich", "uns", "euch"],
    answer: 1,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3209494108",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t3-104",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Es wundert ____ nicht, dass ich noch immer die Äste hinter mir knistern höre",
    options: ["dich", "sich", "mich", "uns"],
    answer: 2,
    metadata: {
      cefr: "B2",
      system: "verb",
      module: "reflexives",
      tier: 3,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4103334907",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
];
