/* eslint-disable */
// Auto-generated by scripts/generate-content.ts — do not edit by hand.
import type { ExerciseItem } from "@/lib/content/schema";

export const reflexivesTier1: ExerciseItem[] = [
  {
    "id": "vb-ref-t1-001",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie redet die ganze Zeit über ____.",
    "options": [
      "sich",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3969480056"
    }
  },
  {
    "id": "vb-ref-t1-002",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir haben ____ vor drei Jahren kennengelernt.",
    "options": [
      "euch",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1156895158"
    }
  },
  {
    "id": "vb-ref-t1-003",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er stand da und sah ____ an.",
    "options": [
      "euch",
      "uns",
      "mich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3287014356"
    }
  },
  {
    "id": "vb-ref-t1-004",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich frage ____, wie lange es dauern wird.",
    "options": [
      "mich",
      "dich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1364192436"
    }
  },
  {
    "id": "vb-ref-t1-005",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ja, ich verstehe ____ gut.",
    "options": [
      "uns",
      "euch",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1993206172"
    }
  },
  {
    "id": "vb-ref-t1-006",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jane schloss ____ im Badezimmer ein.",
    "options": [
      "dich",
      "sich",
      "uns",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:972363557"
    }
  },
  {
    "id": "vb-ref-t1-007",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir können ____ nicht helfen.",
    "options": [
      "uns",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1915847210"
    }
  },
  {
    "id": "vb-ref-t1-008",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lass ____ zusammen essen gehen.",
    "options": [
      "sich",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2604648259"
    }
  },
  {
    "id": "vb-ref-t1-009",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir können es ____ nicht erlauben, noch mehr Zeit zu vertun.",
    "options": [
      "mich",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3881792218"
    }
  },
  {
    "id": "vb-ref-t1-010",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Falls etwas passiert, kannst du ____ gerne anrufen.",
    "options": [
      "dich",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1074813189"
    }
  },
  {
    "id": "vb-ref-t1-011",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich sprach mit ihm auf Englisch und fand, dass ich ____ verständlich machen konnte.",
    "options": [
      "euch",
      "mich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1746888424"
    }
  },
  {
    "id": "vb-ref-t1-012",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lasst ____ diesen Weg gehen.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3419989674"
    }
  },
  {
    "id": "vb-ref-t1-013",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Was habt ihr heute für ____?",
    "options": [
      "mich",
      "sich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2259311697"
    }
  },
  {
    "id": "vb-ref-t1-014",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fühle ____ schuldig, weil ich gelogen habe.",
    "options": [
      "mich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2506560896"
    }
  },
  {
    "id": "vb-ref-t1-015",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie wollen ____ nicht teilnehmen lassen.",
    "options": [
      "mich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2309966059"
    }
  },
  {
    "id": "vb-ref-t1-016",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Teilen Sie das Geld unter ____ auf!",
    "options": [
      "sich",
      "mich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2742634935"
    }
  },
  {
    "id": "vb-ref-t1-017",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ihr werdet ____ wohl nicht amüsieren.",
    "options": [
      "euch",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3382669872"
    }
  },
  {
    "id": "vb-ref-t1-018",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich frage ____, ob John klar ist, wie einsam ich bin.",
    "options": [
      "dich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4052102032"
    }
  },
  {
    "id": "vb-ref-t1-019",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Menschen brachten ____ nicht absichtlich her.",
    "options": [
      "mich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1111577440"
    }
  },
  {
    "id": "vb-ref-t1-020",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Können Sie ____ die Welt ohne Geld vorstellen?",
    "options": [
      "euch",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2822379448"
    }
  },
  {
    "id": "vb-ref-t1-021",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir hören ____ oft singen.",
    "options": [
      "sich",
      "dich",
      "euch",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2066081023"
    }
  },
  {
    "id": "vb-ref-t1-022",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich werde diesen Kuchen für ____ selbst behalten",
    "options": [
      "sich",
      "uns",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:296793745"
    }
  },
  {
    "id": "vb-ref-t1-023",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich frage ____, wieso Eier im Dutzend verkauft werden.",
    "options": [
      "dich",
      "sich",
      "euch",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1766417762"
    }
  },
  {
    "id": "vb-ref-t1-024",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Können Sie ____ einen Extrarabatt von % geben, falls wir von diesem Artikel Stück nehmen?",
    "options": [
      "euch",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1650705135"
    }
  },
  {
    "id": "vb-ref-t1-025",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe euch ja gesagt, dass John ____ helfen würde.",
    "options": [
      "uns",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3845931774"
    }
  },
  {
    "id": "vb-ref-t1-026",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John kann nicht auf ____ warten.",
    "options": [
      "dich",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1192956257"
    }
  },
  {
    "id": "vb-ref-t1-027",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jemand musste ____ zur Vernunft bringen.",
    "options": [
      "sich",
      "uns",
      "euch",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:574437817"
    }
  },
  {
    "id": "vb-ref-t1-028",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er lässt ____ einmal im Monat die Haare schneiden.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2335730360"
    }
  },
  {
    "id": "vb-ref-t1-029",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich wünsche ____ viel Glück.",
    "options": [
      "sich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4028255255"
    }
  },
  {
    "id": "vb-ref-t1-030",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Nur Wasser für ____, danke.",
    "options": [
      "mich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:670309945"
    }
  },
  {
    "id": "vb-ref-t1-031",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Darauf müssen wir ____ konzentrieren.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1032609500"
    }
  },
  {
    "id": "vb-ref-t1-032",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dann hörte John Schritte hinter ____.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3059348239"
    }
  },
  {
    "id": "vb-ref-t1-033",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er wartet dort oben auf ____.",
    "options": [
      "sich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:687226982"
    }
  },
  {
    "id": "vb-ref-t1-034",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir müssen ____ hier nicht sorgen.",
    "options": [
      "dich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3551332173"
    }
  },
  {
    "id": "vb-ref-t1-035",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Das Kleid ist zu kurz für ____.",
    "options": [
      "dich",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3159899214"
    }
  },
  {
    "id": "vb-ref-t1-036",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Doch, darum brauchst du ____.",
    "options": [
      "euch",
      "mich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1461240106"
    }
  },
  {
    "id": "vb-ref-t1-037",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Mensch hat ____ seit der Steinzeit nicht allzu sehr verändert.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1006951743"
    }
  },
  {
    "id": "vb-ref-t1-038",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dann werde ich ____ also verlassen.",
    "options": [
      "euch",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3213862073"
    }
  },
  {
    "id": "vb-ref-t1-039",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Deshalb lasse ich ____ hier schlafen.",
    "options": [
      "uns",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4184279256"
    }
  },
  {
    "id": "vb-ref-t1-040",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Auf Wiedersehen. Du wirst ____ nicht wiedersehen.",
    "options": [
      "uns",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:416898310"
    }
  },
  {
    "id": "vb-ref-t1-041",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er brachte ____ während der ganzen Woche in seinem kleinen Haus unter.",
    "options": [
      "uns",
      "dich",
      "mich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3035030950"
    }
  },
  {
    "id": "vb-ref-t1-042",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die befinden ____ im Gang Nummer zwei.",
    "options": [
      "sich",
      "dich",
      "uns",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2754838513"
    }
  },
  {
    "id": "vb-ref-t1-043",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich möchte ____ für unser letztes Zusammentreffen entschuldigen.",
    "options": [
      "mich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1212639528"
    }
  },
  {
    "id": "vb-ref-t1-044",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lass ____ mal ein Auge drauf werfen.",
    "options": [
      "mich",
      "euch",
      "sich",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3344912032"
    }
  },
  {
    "id": "vb-ref-t1-045",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie baten ____ hierher zu kommen.",
    "options": [
      "dich",
      "euch",
      "uns",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:47136538"
    }
  },
  {
    "id": "vb-ref-t1-046",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er wollte ____ zuerst nicht reinlassen.",
    "options": [
      "mich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:82258703"
    }
  },
  {
    "id": "vb-ref-t1-047",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir lieben ____ nicht mehr.",
    "options": [
      "euch",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2202492096"
    }
  },
  {
    "id": "vb-ref-t1-048",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John verkleidete ____ zu Halloween als ein Mädchen.",
    "options": [
      "euch",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1905066614"
    }
  },
  {
    "id": "vb-ref-t1-049",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Und nennen Sie ____ nicht so.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1859490660"
    }
  },
  {
    "id": "vb-ref-t1-050",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Obwohl der Doktor sein Bestes gab, erholte ____ der Patient nur langsam.",
    "options": [
      "mich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:295281613"
    }
  },
  {
    "id": "vb-ref-t1-051",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Gedanke allein macht ____ krank.",
    "options": [
      "uns",
      "euch",
      "sich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3358590265"
    }
  },
  {
    "id": "vb-ref-t1-052",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ihr müsst ____ eine Suite buchen.",
    "options": [
      "dich",
      "uns",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3279716279"
    }
  },
  {
    "id": "vb-ref-t1-053",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Stell dir vor, dein Vater würde ____ zusammen sehen, was würde er sagen?",
    "options": [
      "euch",
      "sich",
      "uns",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4066715405"
    }
  },
  {
    "id": "vb-ref-t1-054",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Können wir ____ irgendwo unterhalten?",
    "options": [
      "euch",
      "sich",
      "uns",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2953438933"
    }
  },
  {
    "id": "vb-ref-t1-055",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er wurde böse auf ____.",
    "options": [
      "euch",
      "mich",
      "sich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1345641142"
    }
  },
  {
    "id": "vb-ref-t1-056",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Mist, sie haben ____ entdeckt.",
    "options": [
      "mich",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:884557626"
    }
  },
  {
    "id": "vb-ref-t1-057",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es sind alle sehr stolz auf ____.",
    "options": [
      "mich",
      "sich",
      "euch",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2776649294"
    }
  },
  {
    "id": "vb-ref-t1-058",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Diese Nachricht macht ____ traurig.",
    "options": [
      "mich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3071511907"
    }
  },
  {
    "id": "vb-ref-t1-059",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John wird ____ nicht ändern.",
    "options": [
      "euch",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3424019554"
    }
  },
  {
    "id": "vb-ref-t1-060",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er hat ____ eine lustige Geschichte erzählt.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3532804655"
    }
  },
  {
    "id": "vb-ref-t1-061",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es ist fast unmöglich, ____ als Manga-Künstler seinen Lebensunterhalt zu verdienen.",
    "options": [
      "mich",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3977620130"
    }
  },
  {
    "id": "vb-ref-t1-062",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Das Bild erinnert ____ an meine Studentenzeit.",
    "options": [
      "uns",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3502501885"
    }
  },
  {
    "id": "vb-ref-t1-063",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich hatte nie die Absicht, ____ zu verletzen.",
    "options": [
      "mich",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2918836104"
    }
  },
  {
    "id": "vb-ref-t1-064",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "In ihrem Herzen rührte ____ plötzlich Mitleid für das Kind.",
    "options": [
      "uns",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:655257705"
    }
  },
  {
    "id": "vb-ref-t1-065",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir müssen ____ um das Problem kümmern.",
    "options": [
      "dich",
      "uns",
      "euch",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3253781890"
    }
  },
  {
    "id": "vb-ref-t1-066",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wecke ____ um sieben auf.",
    "options": [
      "uns",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3923651060"
    }
  },
  {
    "id": "vb-ref-t1-067",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John sagt, er habe im Augenblick nicht sehr viel Geld bei ____.",
    "options": [
      "uns",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:918859100"
    }
  },
  {
    "id": "vb-ref-t1-068",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Kannst du John nicht einfach bitten, ____ zu helfen?",
    "options": [
      "euch",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:322354208"
    }
  },
  {
    "id": "vb-ref-t1-069",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John macht ____ Sorgen um deine Sicherheit.",
    "options": [
      "dich",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3812300185"
    }
  },
  {
    "id": "vb-ref-t1-070",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wünschen Sie ____, Sie könnten in den Weltraum reisen?",
    "options": [
      "sich",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1491373360"
    }
  },
  {
    "id": "vb-ref-t1-071",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jane wird ____ nicht fangen.",
    "options": [
      "mich",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2933031146"
    }
  },
  {
    "id": "vb-ref-t1-072",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Das Haus ist zu groß für ____ und außerdem ist es zu teuer.",
    "options": [
      "mich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3748780345"
    }
  },
  {
    "id": "vb-ref-t1-073",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er hat ____ im vergangenen Monat von seiner Frau scheiden lassen.",
    "options": [
      "mich",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3550969507"
    }
  },
  {
    "id": "vb-ref-t1-074",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lassen Sie ____ hier anfangen!",
    "options": [
      "euch",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1102813461"
    }
  },
  {
    "id": "vb-ref-t1-075",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fühle ____ tatsächlich etwas krank.",
    "options": [
      "uns",
      "mich",
      "euch",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1838483499"
    }
  },
  {
    "id": "vb-ref-t1-076",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John beschloss für ____, dass es nicht nötig sei, Vitamine einzunehmen.",
    "options": [
      "mich",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:757454218"
    }
  },
  {
    "id": "vb-ref-t1-077",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich würde ____ irgendwann sehr gerne singen hören.",
    "options": [
      "uns",
      "dich",
      "mich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1727300046"
    }
  },
  {
    "id": "vb-ref-t1-078",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es zielt direkt auf ____.",
    "options": [
      "euch",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2794826048"
    }
  },
  {
    "id": "vb-ref-t1-079",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe ____ in den Tunneln schreien gehört.",
    "options": [
      "uns",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2156184796"
    }
  },
  {
    "id": "vb-ref-t1-080",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Kannst du mir sagen, wo auf dieser Karte ich ____ befinde?",
    "options": [
      "dich",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1733325211"
    }
  },
  {
    "id": "vb-ref-t1-081",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Diesmal hast du ____ selbst übertroffen.",
    "options": [
      "dich",
      "sich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4231496833"
    }
  },
  {
    "id": "vb-ref-t1-082",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Hoffentlich verirrst du ____ nicht.",
    "options": [
      "dich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3599694057"
    }
  },
  {
    "id": "vb-ref-t1-083",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich wollte ____ einen schönen Abend wünschen.",
    "options": [
      "sich",
      "euch",
      "uns",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3418016087"
    }
  },
  {
    "id": "vb-ref-t1-084",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Erstens fehlen ____ die finanziellen Mittel.",
    "options": [
      "uns",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1482429021"
    }
  },
  {
    "id": "vb-ref-t1-085",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er kann ____ nicht bewegen.",
    "options": [
      "dich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3349736674"
    }
  },
  {
    "id": "vb-ref-t1-086",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die geretteten Flüchtlinge sehnten ____ nach Freiheit.",
    "options": [
      "dich",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2592424818"
    }
  },
  {
    "id": "vb-ref-t1-087",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du musst etwas Geschäftliches für ____ erledigen.",
    "options": [
      "dich",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3324041242"
    }
  },
  {
    "id": "vb-ref-t1-088",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ruf ____ irgendwann mal an.",
    "options": [
      "sich",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3302972907"
    }
  },
  {
    "id": "vb-ref-t1-089",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie müssen ____ vor nichts fürchten.",
    "options": [
      "sich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3402967679"
    }
  },
  {
    "id": "vb-ref-t1-090",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Aber es fühlt ____ so seltsam an.",
    "options": [
      "sich",
      "euch",
      "dich",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3431344708"
    }
  },
  {
    "id": "vb-ref-t1-091",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir beraten Sie gerne und freuen ____ auf Sie.",
    "options": [
      "euch",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3004314009"
    }
  },
  {
    "id": "vb-ref-t1-092",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Hier drin können wir ____ verstecken.",
    "options": [
      "euch",
      "dich",
      "uns",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1620525114"
    }
  },
  {
    "id": "vb-ref-t1-093",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John konnte ____ nicht vorstellen, jemanden zu erschießen.",
    "options": [
      "sich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1679711308"
    }
  },
  {
    "id": "vb-ref-t1-094",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ihr Geheimnis ist bei ____ sicher.",
    "options": [
      "mich",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:194305301"
    }
  },
  {
    "id": "vb-ref-t1-095",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie erkennen ____ und Jane natürlich nicht.",
    "options": [
      "uns",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3163704913"
    }
  },
  {
    "id": "vb-ref-t1-096",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich kann ____ zumindest sehen.",
    "options": [
      "uns",
      "dich",
      "sich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2032795967"
    }
  },
  {
    "id": "vb-ref-t1-097",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Was er als Nächstes tat, war für ____ schon eine Überraschung.",
    "options": [
      "dich",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:761082997"
    }
  },
  {
    "id": "vb-ref-t1-098",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie haben nur noch Stunden, um ____ zu entscheiden.",
    "options": [
      "sich",
      "mich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:265198870"
    }
  },
  {
    "id": "vb-ref-t1-099",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Gut, aber beeilen Sie ____.",
    "options": [
      "mich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1494740099"
    }
  },
  {
    "id": "vb-ref-t1-100",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Polizei könnte ____ dafür verhaften.",
    "options": [
      "dich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1198470237"
    }
  },
  {
    "id": "vb-ref-t1-101",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jemand hat versucht, ____ zu ermorden.",
    "options": [
      "euch",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2618615446"
    }
  },
  {
    "id": "vb-ref-t1-102",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe eine Aufgabe für ____.",
    "options": [
      "dich",
      "sich",
      "uns",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1212074593"
    }
  },
  {
    "id": "vb-ref-t1-103",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich kann nicht verstehen, worüber sie ____ beschweren sollte.",
    "options": [
      "euch",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4275848007"
    }
  },
  {
    "id": "vb-ref-t1-104",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er versuchte, ____ zu küssen.",
    "options": [
      "uns",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1413814245"
    }
  },
  {
    "id": "vb-ref-t1-105",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir können ____ Misstrauen nicht leisten.",
    "options": [
      "euch",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:301581636"
    }
  },
  {
    "id": "vb-ref-t1-106",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie kann ____ nicht aufhalten.",
    "options": [
      "uns",
      "sich",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2084551490"
    }
  },
  {
    "id": "vb-ref-t1-107",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ist es ____ nicht in den Sinn gekommen, die Fenster zu schließen?",
    "options": [
      "sich",
      "euch",
      "uns",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:709037680"
    }
  },
  {
    "id": "vb-ref-t1-108",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Davor wollte ich ____ beschützen.",
    "options": [
      "uns",
      "mich",
      "euch",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1483750818"
    }
  },
  {
    "id": "vb-ref-t1-109",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie können ____ im Flugzeug unterhalten.",
    "options": [
      "dich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:952916284"
    }
  },
  {
    "id": "vb-ref-t1-110",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Seine törichten Freunde wollen ____ morgen früh angreifen.",
    "options": [
      "euch",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1423279121"
    }
  },
  {
    "id": "vb-ref-t1-111",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie müssen ____ entspannen und einfach beruhigen.",
    "options": [
      "sich",
      "uns",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:414097969"
    }
  },
  {
    "id": "vb-ref-t1-112",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Mörder hielt ____ in den Bergen versteckt.",
    "options": [
      "euch",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2705779205"
    }
  },
  {
    "id": "vb-ref-t1-113",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Stell ____ in die Reihe.",
    "options": [
      "mich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3973641519"
    }
  },
  {
    "id": "vb-ref-t1-114",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Haltet ____ natürlich vom Fluss fern.",
    "options": [
      "mich",
      "dich",
      "euch",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4170169707"
    }
  },
  {
    "id": "vb-ref-t1-115",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John kann es ____ leisten, jeden Tag in einem teuren Restaurant zu essen.",
    "options": [
      "dich",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1577679503"
    }
  },
  {
    "id": "vb-ref-t1-116",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John glaubte an ____ und ich bin ihm dafür dankbar.",
    "options": [
      "mich",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2738792336"
    }
  },
  {
    "id": "vb-ref-t1-117",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie können es ____ bei diesem Experiment nicht erlauben, unvorsichtig zu sein.",
    "options": [
      "euch",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2597188906"
    }
  },
  {
    "id": "vb-ref-t1-118",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie hämmerten in meinem Kopf und machten ____ wahnsinnig.",
    "options": [
      "euch",
      "mich",
      "sich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2899764234"
    }
  },
  {
    "id": "vb-ref-t1-119",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Kuh gibt ____ Milch.",
    "options": [
      "dich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3418006778"
    }
  },
  {
    "id": "vb-ref-t1-120",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie ist ____ ihrer Schönheit nicht bewusst.",
    "options": [
      "euch",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:804711570"
    }
  },
  {
    "id": "vb-ref-t1-121",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Hausherr beschäftigte ____ schon früh mit Kunst.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:255003239"
    }
  },
  {
    "id": "vb-ref-t1-122",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Priester beteiligte ____ bei den Spielen der Kinder.",
    "options": [
      "sich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1428708386"
    }
  },
  {
    "id": "vb-ref-t1-123",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sein Zustand hat ____ verbessert.",
    "options": [
      "uns",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:281156892"
    }
  },
  {
    "id": "vb-ref-t1-124",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John fragte ____, woran Jane wohl dachte.",
    "options": [
      "euch",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3734259580"
    }
  },
  {
    "id": "vb-ref-t1-125",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Kapitän des Schiffes entschied ____ den Kurs zu ändern.",
    "options": [
      "uns",
      "sich",
      "euch",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3711311194"
    }
  },
  {
    "id": "vb-ref-t1-126",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich frage ____, weshalb sie John gewählt haben.",
    "options": [
      "uns",
      "sich",
      "euch",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1831838154"
    }
  },
  {
    "id": "vb-ref-t1-127",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir bewegen ____ nach Norden.",
    "options": [
      "mich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3019332818"
    }
  },
  {
    "id": "vb-ref-t1-128",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich werde für ____ beten.",
    "options": [
      "sich",
      "euch",
      "mich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2814494202"
    }
  },
  {
    "id": "vb-ref-t1-129",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Menschliche Wesen unterscheiden ____ von den Tieren dadurch, dass sie denken und sprechen können.",
    "options": [
      "mich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1353731842"
    }
  },
  {
    "id": "vb-ref-t1-130",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Meine Zunge fühlte ____ behaart an.",
    "options": [
      "dich",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4170640966"
    }
  },
  {
    "id": "vb-ref-t1-131",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du wirst ____ nicht bemerken.",
    "options": [
      "sich",
      "mich",
      "euch",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1676886943"
    }
  },
  {
    "id": "vb-ref-t1-132",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich liebe ____ für immer und ewig. Amen.",
    "options": [
      "euch",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2816986136"
    }
  },
  {
    "id": "vb-ref-t1-133",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lege ____ auf den Bauch.",
    "options": [
      "mich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:858952642"
    }
  },
  {
    "id": "vb-ref-t1-134",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dann musst du ____ decken.",
    "options": [
      "euch",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2655296898"
    }
  },
  {
    "id": "vb-ref-t1-135",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir müssen ____ auf das Schlimmste vorbereiten.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2984855791"
    }
  },
  {
    "id": "vb-ref-t1-136",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich werde es für ____ klauen.",
    "options": [
      "dich",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1878221436"
    }
  },
  {
    "id": "vb-ref-t1-137",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie möchte mit ____ allen etwas besprechen.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3333628524"
    }
  },
  {
    "id": "vb-ref-t1-138",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich versprach über ____ zu wachen.",
    "options": [
      "uns",
      "sich",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:884787105"
    }
  },
  {
    "id": "vb-ref-t1-139",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Diese Sitte ist ____ fremd.",
    "options": [
      "dich",
      "mich",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1289005072"
    }
  },
  {
    "id": "vb-ref-t1-140",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich wollte ____ nicht eifersüchtig machen.",
    "options": [
      "mich",
      "euch",
      "sich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3024450965"
    }
  },
  {
    "id": "vb-ref-t1-141",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie können sich jederzeit an ____ wenden.",
    "options": [
      "sich",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2172498154"
    }
  },
  {
    "id": "vb-ref-t1-142",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie wollte ____ auseinander bringen.",
    "options": [
      "uns",
      "sich",
      "euch",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3515704571"
    }
  },
  {
    "id": "vb-ref-t1-143",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Niemand kann ____ hier kontrollieren.",
    "options": [
      "dich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1097049713"
    }
  },
  {
    "id": "vb-ref-t1-144",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lasst ____ weitermachen, wenn John einverstanden ist.",
    "options": [
      "dich",
      "uns",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1436895573"
    }
  },
  {
    "id": "vb-ref-t1-145",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dinge, die ____ aufregen sollten, prallen einfach von mir ab.",
    "options": [
      "sich",
      "dich",
      "uns",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:155107647"
    }
  },
  {
    "id": "vb-ref-t1-146",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Fehler zu machen, macht ____ menschlich.",
    "options": [
      "mich",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1699105003"
    }
  },
  {
    "id": "vb-ref-t1-147",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich unterwerfe ____ der Gnade des Gerichts.",
    "options": [
      "uns",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3172477972"
    }
  },
  {
    "id": "vb-ref-t1-148",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die sind zu fein für ____.",
    "options": [
      "mich",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:958489307"
    }
  },
  {
    "id": "vb-ref-t1-149",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du musst ihn für ____ festhalten.",
    "options": [
      "mich",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2402567132"
    }
  },
  {
    "id": "vb-ref-t1-150",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir sollten ____ jetzt drum kümmern.",
    "options": [
      "mich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2231200701"
    }
  },
  {
    "id": "vb-ref-t1-151",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Da kann ich ____ besser verteidigen.",
    "options": [
      "uns",
      "euch",
      "dich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4061566525"
    }
  },
  {
    "id": "vb-ref-t1-152",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich erwog, die Arbeit zu wechseln, doch letztlich entschied ich ____ dagegen.",
    "options": [
      "sich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2922607690"
    }
  },
  {
    "id": "vb-ref-t1-153",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie können ____ entweder beschützen oder vernichten.",
    "options": [
      "dich",
      "uns",
      "euch",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4151760371"
    }
  },
  {
    "id": "vb-ref-t1-154",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie erinnern ____ an einen entfernten Cousin.",
    "options": [
      "dich",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2855570100"
    }
  },
  {
    "id": "vb-ref-t1-155",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie halten ____ alle für einen Narren.",
    "options": [
      "dich",
      "uns",
      "euch",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:118956532"
    }
  },
  {
    "id": "vb-ref-t1-156",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John wäscht ____ stets die Hände, bevor er etwas isst.",
    "options": [
      "dich",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:422313978"
    }
  },
  {
    "id": "vb-ref-t1-157",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Ratte hat ____ heute sitzen lassen.",
    "options": [
      "dich",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2585508931"
    }
  },
  {
    "id": "vb-ref-t1-158",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er war ____ der Gefahr bewusst.",
    "options": [
      "euch",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3322591768"
    }
  },
  {
    "id": "vb-ref-t1-159",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Kann ich ____ irgendwie überzeugen?",
    "options": [
      "dich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3225664642"
    }
  },
  {
    "id": "vb-ref-t1-160",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Unsere Gäste fühlen ____ bestens versorgt.",
    "options": [
      "euch",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3785478588"
    }
  },
  {
    "id": "vb-ref-t1-161",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Kinder beschuldigten ____ gegenseitig.",
    "options": [
      "euch",
      "dich",
      "mich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1281281649"
    }
  },
  {
    "id": "vb-ref-t1-162",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wisst ihr, wo wir ____ befinden?",
    "options": [
      "sich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:27181478"
    }
  },
  {
    "id": "vb-ref-t1-163",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Gedanke macht ____ krank.",
    "options": [
      "euch",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3148835434"
    }
  },
  {
    "id": "vb-ref-t1-164",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jetzt wird sie ____ bestimmt entspannen.",
    "options": [
      "mich",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2028350575"
    }
  },
  {
    "id": "vb-ref-t1-165",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jetzt lass ____ zur Schule eilen.",
    "options": [
      "mich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3663440981"
    }
  },
  {
    "id": "vb-ref-t1-166",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John, du kannst ____ umdrehen.",
    "options": [
      "uns",
      "dich",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3502046906"
    }
  },
  {
    "id": "vb-ref-t1-167",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie möchten ____ nicht loswerden.",
    "options": [
      "euch",
      "sich",
      "dich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:665562855"
    }
  },
  {
    "id": "vb-ref-t1-168",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "An kalten Tagen können Sie bei ____ ein elektrisches Heizgerät mieten.",
    "options": [
      "mich",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1844949419"
    }
  },
  {
    "id": "vb-ref-t1-169",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du kannst ____ nicht dafür bestrafen.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2757857191"
    }
  },
  {
    "id": "vb-ref-t1-170",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John kann ____ nicht konzentrieren.",
    "options": [
      "sich",
      "mich",
      "euch",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4035519743"
    }
  },
  {
    "id": "vb-ref-t1-171",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Eigentlich wollte ich ____ heute beeindrucken.",
    "options": [
      "dich",
      "uns",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:231783380"
    }
  },
  {
    "id": "vb-ref-t1-172",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es ist nicht an ____ das Urteil zu fällen.",
    "options": [
      "dich",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3635487419"
    }
  },
  {
    "id": "vb-ref-t1-173",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ihr werdet ____ daran gewöhnen.",
    "options": [
      "uns",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2072600844"
    }
  },
  {
    "id": "vb-ref-t1-174",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du musst ____ auf deine Stärken besinnen.",
    "options": [
      "euch",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1243497378"
    }
  },
  {
    "id": "vb-ref-t1-175",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es bringt ____ weder Geld noch Ruhm.",
    "options": [
      "uns",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:893194758"
    }
  },
  {
    "id": "vb-ref-t1-176",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du kannst ____ hier nicht einsperren.",
    "options": [
      "euch",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 1,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4005991445"
    }
  }
];
