/* eslint-disable */
// Auto-generated by scripts/generate-content.ts — do not edit by hand.
import type { ExerciseItem } from "@/lib/content/schema";

export const reflexivesTier2: ExerciseItem[] = [
  {
    "id": "vb-ref-t2-001",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es ist unhöflich, ____ über seinen Chef in der Öffentlichkeit lustig zu machen.",
    "options": [
      "mich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2260789383"
    }
  },
  {
    "id": "vb-ref-t2-002",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du möchtest ____ nicht einmal verabschieden.",
    "options": [
      "euch",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3383524461"
    }
  },
  {
    "id": "vb-ref-t2-003",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Mögen Sie ____ mit Glück segnen.",
    "options": [
      "dich",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3682513764"
    }
  },
  {
    "id": "vb-ref-t2-004",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Möbel aus gutem Material verkaufen ____ gut.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:59318089"
    }
  },
  {
    "id": "vb-ref-t2-005",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wie manche von ____ wissen, ist mein Vater etwas unheimlich.",
    "options": [
      "euch",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3573553096"
    }
  },
  {
    "id": "vb-ref-t2-006",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dein neuer Liebhaber ließ ____ echt aufblühen.",
    "options": [
      "dich",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3475345510"
    }
  },
  {
    "id": "vb-ref-t2-007",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Und niemand wird jemals ____ verdächtigen.",
    "options": [
      "dich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2861508525"
    }
  },
  {
    "id": "vb-ref-t2-008",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Umstände haben ____ geändert.",
    "options": [
      "dich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2248742837"
    }
  },
  {
    "id": "vb-ref-t2-009",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Warum fragst du ausgerechnet ____?",
    "options": [
      "uns",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1787334607"
    }
  },
  {
    "id": "vb-ref-t2-010",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Hier kann man ____ nirgendwo hinsetzen.",
    "options": [
      "mich",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2263058465"
    }
  },
  {
    "id": "vb-ref-t2-011",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jane verspätete ____ aufgrund des Sturms.",
    "options": [
      "sich",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3868667236"
    }
  },
  {
    "id": "vb-ref-t2-012",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Situation hat ____ dramatisch geändert.",
    "options": [
      "mich",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2426254916"
    }
  },
  {
    "id": "vb-ref-t2-013",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Vorhin habt ihr ____ seufzen hören.",
    "options": [
      "mich",
      "sich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:672165451"
    }
  },
  {
    "id": "vb-ref-t2-014",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Gewinner kämpft morgen gegen ____.",
    "options": [
      "uns",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3461410426"
    }
  },
  {
    "id": "vb-ref-t2-015",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Entspannen Sie ____, ich könnte niemals so grausam sein.",
    "options": [
      "euch",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1523403751"
    }
  },
  {
    "id": "vb-ref-t2-016",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Möglicherweise müssen Sie ____ dann wecken.",
    "options": [
      "uns",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2774472537"
    }
  },
  {
    "id": "vb-ref-t2-017",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du musst ____ hindurch leiten.",
    "options": [
      "euch",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1501526413"
    }
  },
  {
    "id": "vb-ref-t2-018",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Diese wilde Bestie nennt ____ Hauskatze.",
    "options": [
      "euch",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1591948726"
    }
  },
  {
    "id": "vb-ref-t2-019",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich bin froh, dass ich ____ amüsiere.",
    "options": [
      "uns",
      "dich",
      "euch",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3263222934"
    }
  },
  {
    "id": "vb-ref-t2-020",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Mein Mann hat ____ entschieden, sich von mir scheiden zu lassen.",
    "options": [
      "sich",
      "mich",
      "euch",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3247448538"
    }
  },
  {
    "id": "vb-ref-t2-021",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lass ____ stattdessen Karten spielen.",
    "options": [
      "dich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3811932225"
    }
  },
  {
    "id": "vb-ref-t2-022",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich möchte ____ keinen Ärger bereiten.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:389551309"
    }
  },
  {
    "id": "vb-ref-t2-023",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Aber meine Mutter wollte ____ alle kennenlernen.",
    "options": [
      "uns",
      "euch",
      "sich",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3903621923"
    }
  },
  {
    "id": "vb-ref-t2-024",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Trainer ließ ____ drei zusätzliche Runden laufen.",
    "options": [
      "mich",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3149328296"
    }
  },
  {
    "id": "vb-ref-t2-025",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Natürlich bilden ____ jetzt langsam Schlangen.",
    "options": [
      "euch",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2292566852"
    }
  },
  {
    "id": "vb-ref-t2-026",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Nun, der Plan ist, ____ zu erschöpfen.",
    "options": [
      "uns",
      "euch",
      "mich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2524115153"
    }
  },
  {
    "id": "vb-ref-t2-027",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lass es ____ nochmals probieren.",
    "options": [
      "euch",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1211903152"
    }
  },
  {
    "id": "vb-ref-t2-028",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du strafst nur ____ selbst.",
    "options": [
      "uns",
      "euch",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2328574971"
    }
  },
  {
    "id": "vb-ref-t2-029",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich sehe ____ später, Junior.",
    "options": [
      "sich",
      "euch",
      "uns",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1104599389"
    }
  },
  {
    "id": "vb-ref-t2-030",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er versteht ____ gut mit seinen Mitarbeitern.",
    "options": [
      "mich",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1917763586"
    }
  },
  {
    "id": "vb-ref-t2-031",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich werde ____ nicht vergewaltigen.",
    "options": [
      "uns",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:636700010"
    }
  },
  {
    "id": "vb-ref-t2-032",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er wird ____ hier rausholen.",
    "options": [
      "uns",
      "dich",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:985567717"
    }
  },
  {
    "id": "vb-ref-t2-033",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Jane war außer ____ vor Aufregung.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:80793227"
    }
  },
  {
    "id": "vb-ref-t2-034",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich will ____ nicht hereinlegen.",
    "options": [
      "mich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2779382856"
    }
  },
  {
    "id": "vb-ref-t2-035",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du solltest ____ auch schämen.",
    "options": [
      "dich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3731003823"
    }
  },
  {
    "id": "vb-ref-t2-036",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ein langer Marsch liegt vor ____.",
    "options": [
      "sich",
      "uns",
      "dich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2576756912"
    }
  },
  {
    "id": "vb-ref-t2-037",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich muss ____ um mein Vieh kümmern.",
    "options": [
      "sich",
      "uns",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:663326337"
    }
  },
  {
    "id": "vb-ref-t2-038",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich war schüchtern und habe ____ mit keinem einzigen Deutschen angefreundet.",
    "options": [
      "sich",
      "uns",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:141354208"
    }
  },
  {
    "id": "vb-ref-t2-039",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Bitte lass es ____ bis Mittwoch wissen, wenn du nicht teilnehmen kannst.",
    "options": [
      "mich",
      "sich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:428868412"
    }
  },
  {
    "id": "vb-ref-t2-040",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Unsere Mannschaft hat ____ sehr gut geschlagen.",
    "options": [
      "mich",
      "sich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4081611847"
    }
  },
  {
    "id": "vb-ref-t2-041",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wenn wir ____ ihnen nähern, verschwinden sie.",
    "options": [
      "sich",
      "mich",
      "uns",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3125176435"
    }
  },
  {
    "id": "vb-ref-t2-042",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lasst ____ mit Kapitel beginnen.",
    "options": [
      "sich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2860076154"
    }
  },
  {
    "id": "vb-ref-t2-043",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "In diesem Punkt könnte ich ____ vielleicht irren.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:622776277"
    }
  },
  {
    "id": "vb-ref-t2-044",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Inzwischen werden Hunger und Durst ____ schwächen.",
    "options": [
      "dich",
      "euch",
      "uns",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3725715352"
    }
  },
  {
    "id": "vb-ref-t2-045",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie scheinen entschlossen, ____ fremd bleiben zu wollen.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4211781173"
    }
  },
  {
    "id": "vb-ref-t2-046",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du solltest bei ____ mitmachen.",
    "options": [
      "dich",
      "sich",
      "euch",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3629111478"
    }
  },
  {
    "id": "vb-ref-t2-047",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Andere historische Gebäude lohnen ____ zu sehen.",
    "options": [
      "dich",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1628488644"
    }
  },
  {
    "id": "vb-ref-t2-048",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir platzierten ____ in den Stühlen neben dem Ausgang.",
    "options": [
      "dich",
      "uns",
      "mich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:387446331"
    }
  },
  {
    "id": "vb-ref-t2-049",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John, ich hatte ____ gebeten, nicht diese nervige Melodie zu pfeifen.",
    "options": [
      "dich",
      "mich",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1055738799"
    }
  },
  {
    "id": "vb-ref-t2-050",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir bemühen ____ derzeit, den normalen Service möglichst schnell wiederherzustellen.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4205359190"
    }
  },
  {
    "id": "vb-ref-t2-051",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich denke, es ist gut, dass Bücher noch existieren, aber sie machen ____ schläfrig.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:918988775"
    }
  },
  {
    "id": "vb-ref-t2-052",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich muss ____ dafür bedanken.",
    "options": [
      "mich",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:109907923"
    }
  },
  {
    "id": "vb-ref-t2-053",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du bist widerlich und ich hasse ____.",
    "options": [
      "uns",
      "sich",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3198013958"
    }
  },
  {
    "id": "vb-ref-t2-054",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Aber ich möchte ____ mit ihm befreunden.",
    "options": [
      "dich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1870754201"
    }
  },
  {
    "id": "vb-ref-t2-055",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John wird kaum mit ____ rechnen.",
    "options": [
      "euch",
      "mich",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2114888967"
    }
  },
  {
    "id": "vb-ref-t2-056",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Letztendlich sind wir ____ doch bei etwas einig.",
    "options": [
      "euch",
      "mich",
      "uns",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1547708463"
    }
  },
  {
    "id": "vb-ref-t2-057",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie sollen ____ einen Film aussuchen.",
    "options": [
      "mich",
      "sich",
      "uns",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2732795792"
    }
  },
  {
    "id": "vb-ref-t2-058",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Letztendlich wird jemand John sagen müssen, dass er ____ zu benehmen hat.",
    "options": [
      "sich",
      "dich",
      "uns",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:133233628"
    }
  },
  {
    "id": "vb-ref-t2-059",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "In Libyen ereignet ____ gegenwärtig eine zweifache Tragödie.",
    "options": [
      "sich",
      "mich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2642020475"
    }
  },
  {
    "id": "vb-ref-t2-060",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Lehrer bat ____, jeden Tag unser Klassenzimmer zu putzen.",
    "options": [
      "euch",
      "uns",
      "mich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:55515144"
    }
  },
  {
    "id": "vb-ref-t2-061",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dann hob er die Hand, um ____ zu unterbrechen.",
    "options": [
      "dich",
      "mich",
      "euch",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1148699834"
    }
  },
  {
    "id": "vb-ref-t2-062",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie werden ____ zum Schnaps einladen.",
    "options": [
      "mich",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2977100166"
    }
  },
  {
    "id": "vb-ref-t2-063",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir könnten ____ ein Motel suchen.",
    "options": [
      "uns",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4008202122"
    }
  },
  {
    "id": "vb-ref-t2-064",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich will ____ da nicht verwickeln lassen.",
    "options": [
      "mich",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2562354535"
    }
  },
  {
    "id": "vb-ref-t2-065",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich muss ____ hinlegen und schlafen.",
    "options": [
      "uns",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4101428935"
    }
  },
  {
    "id": "vb-ref-t2-066",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John schrieb ____ Janes Telefonnummer auf.",
    "options": [
      "mich",
      "uns",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:439607835"
    }
  },
  {
    "id": "vb-ref-t2-067",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Richte ____ gefälligst danach!",
    "options": [
      "uns",
      "dich",
      "euch",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1434114111"
    }
  },
  {
    "id": "vb-ref-t2-068",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fühle ____ mies wegen gestern.",
    "options": [
      "uns",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1117362521"
    }
  },
  {
    "id": "vb-ref-t2-069",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er war so lieb ____ zu verpflichten.",
    "options": [
      "euch",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2915253986"
    }
  },
  {
    "id": "vb-ref-t2-070",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich möchte ____ nicht in dich verlieben.",
    "options": [
      "euch",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4060216802"
    }
  },
  {
    "id": "vb-ref-t2-071",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Kann irgendwer ____ auf hilfreiche Informationen hinweisen?",
    "options": [
      "sich",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2394574002"
    }
  },
  {
    "id": "vb-ref-t2-072",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe einen Kater und erinnere ____ nicht mehr an die Party.",
    "options": [
      "euch",
      "uns",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1504981420"
    }
  },
  {
    "id": "vb-ref-t2-073",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Derzeit beteiligen ____ insgesamt Länder.",
    "options": [
      "mich",
      "dich",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:554587729"
    }
  },
  {
    "id": "vb-ref-t2-074",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sein Schwiegersohn hat ____ vollständig von seiner Krankheit erholt.",
    "options": [
      "mich",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1014212985"
    }
  },
  {
    "id": "vb-ref-t2-075",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Versuch nicht, ____ zu ärgern!",
    "options": [
      "euch",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:859735456"
    }
  },
  {
    "id": "vb-ref-t2-076",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es fühlt ____ mehr wie ein Akt der Verzweiflung an.",
    "options": [
      "mich",
      "sich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2530119885"
    }
  },
  {
    "id": "vb-ref-t2-077",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe auf ____ in unserer Kabine gewartet.",
    "options": [
      "dich",
      "euch",
      "uns",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1793472593"
    }
  },
  {
    "id": "vb-ref-t2-078",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er kann auf ____ nicht verzichten.",
    "options": [
      "dich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3243500109"
    }
  },
  {
    "id": "vb-ref-t2-079",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich habe ____ um eine Kleinigkeit gebeten.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:806302504"
    }
  },
  {
    "id": "vb-ref-t2-080",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wasser und Luft umgeben ____ überall.",
    "options": [
      "uns",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3316035729"
    }
  },
  {
    "id": "vb-ref-t2-081",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie werden mit ____ marschieren.",
    "options": [
      "uns",
      "dich",
      "mich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:256654828"
    }
  },
  {
    "id": "vb-ref-t2-082",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fürchte, sie könnte ____ verlaufen haben.",
    "options": [
      "uns",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:210847053"
    }
  },
  {
    "id": "vb-ref-t2-083",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich wollte ____ nicht anlügen.",
    "options": [
      "dich",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2985770545"
    }
  },
  {
    "id": "vb-ref-t2-084",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Deshalb hat man ____ davor zu hüten.",
    "options": [
      "euch",
      "dich",
      "mich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3661097742"
    }
  },
  {
    "id": "vb-ref-t2-085",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich wollte ____ nicht schrecken.",
    "options": [
      "dich",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:824127102"
    }
  },
  {
    "id": "vb-ref-t2-086",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Das lässt ____ alles medizinisch erklären.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2388029775"
    }
  },
  {
    "id": "vb-ref-t2-087",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er hat einen schönen, fetten Wurm für ____.",
    "options": [
      "uns",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1178753504"
    }
  },
  {
    "id": "vb-ref-t2-088",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er ermahnte ____, die Vorschrift zu beachten.",
    "options": [
      "uns",
      "sich",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2364148847"
    }
  },
  {
    "id": "vb-ref-t2-089",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Polizei könnte ____ dafür festnehmen.",
    "options": [
      "dich",
      "sich",
      "uns",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1870030237"
    }
  },
  {
    "id": "vb-ref-t2-090",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du benimmst ____ wie eine billige Hure.",
    "options": [
      "euch",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3875306625"
    }
  },
  {
    "id": "vb-ref-t2-091",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es würde ____ nicht wundern.",
    "options": [
      "euch",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:540182711"
    }
  },
  {
    "id": "vb-ref-t2-092",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Deine Haltung hat ____ definitiv gebessert.",
    "options": [
      "uns",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2956450321"
    }
  },
  {
    "id": "vb-ref-t2-093",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Am Sonntag versammeln ____ alle an dem festlichen Gottesdienst.",
    "options": [
      "euch",
      "uns",
      "mich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2828231633"
    }
  },
  {
    "id": "vb-ref-t2-094",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Gib alles, um ____ zu erregen.",
    "options": [
      "euch",
      "mich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:305896052"
    }
  },
  {
    "id": "vb-ref-t2-095",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Und er sagt, wir verhalten ____ eigenartig.",
    "options": [
      "mich",
      "dich",
      "uns",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2837454924"
    }
  },
  {
    "id": "vb-ref-t2-096",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Renovierung der Stadthalle war ____ völlig unbekannt.",
    "options": [
      "euch",
      "uns",
      "sich",
      "mich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2417995956"
    }
  },
  {
    "id": "vb-ref-t2-097",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich andererseits kann ____ eine Menge bieten.",
    "options": [
      "uns",
      "dich",
      "sich",
      "euch"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3225314173"
    }
  },
  {
    "id": "vb-ref-t2-098",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Die Spannung bringt ____ noch um!",
    "options": [
      "sich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:881584559"
    }
  },
  {
    "id": "vb-ref-t2-099",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Sport bietet den Menschen ausgezeichnete Möglichkeiten, ____ in ihrem unmittelbaren Umfeld zu engagieren.",
    "options": [
      "uns",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3424388145"
    }
  },
  {
    "id": "vb-ref-t2-100",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Setz ____ in die Karre.",
    "options": [
      "euch",
      "uns",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3851441385"
    }
  },
  {
    "id": "vb-ref-t2-101",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wenn es für ____ zu riskant ist, sag es.",
    "options": [
      "uns",
      "euch",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:752073043"
    }
  },
  {
    "id": "vb-ref-t2-102",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fühle ____ nicht mehr sehr britisch, sondern immer schottischer.",
    "options": [
      "mich",
      "dich",
      "uns",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4273182439"
    }
  },
  {
    "id": "vb-ref-t2-103",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Könntest du ____ auch umarmen?",
    "options": [
      "sich",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3602078857"
    }
  },
  {
    "id": "vb-ref-t2-104",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie muss ____ als Wertegemeinschaft erweisen.",
    "options": [
      "euch",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:588734508"
    }
  },
  {
    "id": "vb-ref-t2-105",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Aber ich weiß, du wirst es durchziehen und ____ stolz machen.",
    "options": [
      "mich",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:348289906"
    }
  },
  {
    "id": "vb-ref-t2-106",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du willst ____ doch nicht verirren.",
    "options": [
      "uns",
      "euch",
      "mich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3981544034"
    }
  },
  {
    "id": "vb-ref-t2-107",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Seit vorgestern haben sie andauernd bei ____ angerufen.",
    "options": [
      "dich",
      "sich",
      "uns",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2238473215"
    }
  },
  {
    "id": "vb-ref-t2-108",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Du lässt ____ nicht einmal hierbleiben.",
    "options": [
      "dich",
      "euch",
      "mich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2774985962"
    }
  },
  {
    "id": "vb-ref-t2-109",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er packte ____ am Kragen.",
    "options": [
      "mich",
      "uns",
      "dich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3551922935"
    }
  },
  {
    "id": "vb-ref-t2-110",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir können ____ der Verzweiflung nicht hingeben.",
    "options": [
      "dich",
      "euch",
      "uns",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1347662284"
    }
  },
  {
    "id": "vb-ref-t2-111",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Na ja, ich kann ____ nicht beschweren.",
    "options": [
      "mich",
      "sich",
      "uns",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3592335524"
    }
  },
  {
    "id": "vb-ref-t2-112",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich möchte ____ zum Dinner einladen.",
    "options": [
      "sich",
      "mich",
      "dich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2327570074"
    }
  },
  {
    "id": "vb-ref-t2-113",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Als ich ____ zum ersten Mal trommeln sah, war ich neidisch.",
    "options": [
      "dich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1654435904"
    }
  },
  {
    "id": "vb-ref-t2-114",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich glaube, dass wir ____ eventuell nicht ganz verstanden haben.",
    "options": [
      "mich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1252067104"
    }
  },
  {
    "id": "vb-ref-t2-115",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Dein Freund informiert ____ über die Einzelheiten.",
    "options": [
      "euch",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3275988257"
    }
  },
  {
    "id": "vb-ref-t2-116",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Finden Sie die Stärke und wehren Sie ____.",
    "options": [
      "euch",
      "mich",
      "uns",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3578023771"
    }
  },
  {
    "id": "vb-ref-t2-117",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich fühlte ____ so leicht wie eine Feder.",
    "options": [
      "uns",
      "mich",
      "dich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2214796466"
    }
  },
  {
    "id": "vb-ref-t2-118",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Man kann ____ leicht beeinflussen.",
    "options": [
      "dich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4136444790"
    }
  },
  {
    "id": "vb-ref-t2-119",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie fangen an, ____ zu deprimieren.",
    "options": [
      "uns",
      "mich",
      "euch",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2364422372"
    }
  },
  {
    "id": "vb-ref-t2-120",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John wird morgen gegen ____ aussagen.",
    "options": [
      "euch",
      "sich",
      "dich",
      "mich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4155100073"
    }
  },
  {
    "id": "vb-ref-t2-121",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Lassen Sie ____ bitte noch einmal in Verhandlungen eintreten.",
    "options": [
      "mich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3818192560"
    }
  },
  {
    "id": "vb-ref-t2-122",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Selbst wenn sie ____ umbringen, wird dein Name ewig weiterleben.",
    "options": [
      "euch",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3449276865"
    }
  },
  {
    "id": "vb-ref-t2-123",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Glotzt du ____ oder sie an?",
    "options": [
      "euch",
      "uns",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2121784394"
    }
  },
  {
    "id": "vb-ref-t2-124",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Gerade hat ____ der Vorhang bewegt.",
    "options": [
      "mich",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1538441509"
    }
  },
  {
    "id": "vb-ref-t2-125",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich kann ____ gelegentlich damit identifizieren.",
    "options": [
      "dich",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2771069019"
    }
  },
  {
    "id": "vb-ref-t2-126",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Aber ich kann ____ nicht einfach zurücklassen.",
    "options": [
      "euch",
      "sich",
      "dich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1965212380"
    }
  },
  {
    "id": "vb-ref-t2-127",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie wollten ____ ausrauben und wir entkamen.",
    "options": [
      "sich",
      "euch",
      "dich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1807496863"
    }
  },
  {
    "id": "vb-ref-t2-128",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich muss ____ nur ein wenig umsehen.",
    "options": [
      "euch",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4018146294"
    }
  },
  {
    "id": "vb-ref-t2-129",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Diese Menschen, sie verehren ____.",
    "options": [
      "dich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3332276060"
    }
  },
  {
    "id": "vb-ref-t2-130",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Glücklicherweise habe ich keine, also bietet ____ mir diese spezielle Versuchung nicht.",
    "options": [
      "uns",
      "dich",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2495544790"
    }
  },
  {
    "id": "vb-ref-t2-131",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Adler stürzte ____ auf seine Beute.",
    "options": [
      "mich",
      "uns",
      "sich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2358199780"
    }
  },
  {
    "id": "vb-ref-t2-132",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wenigstens belästigt ____ dein Boss nicht sexuell.",
    "options": [
      "sich",
      "dich",
      "uns",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4118944795"
    }
  },
  {
    "id": "vb-ref-t2-133",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich will ____ überhaupt nicht quälen.",
    "options": [
      "dich",
      "euch",
      "sich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3076882187"
    }
  },
  {
    "id": "vb-ref-t2-134",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Er hatte vier Stunden, um ____ zu erholen.",
    "options": [
      "mich",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1114597938"
    }
  },
  {
    "id": "vb-ref-t2-135",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es handelt ____ also um einen Mittler zwischen Client und Server.",
    "options": [
      "sich",
      "uns",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:4108140085"
    }
  },
  {
    "id": "vb-ref-t2-136",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es juckt ____ und du kannst nicht kratzen.",
    "options": [
      "mich",
      "uns",
      "dich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1217590898"
    }
  },
  {
    "id": "vb-ref-t2-137",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir halten ____ alle für unsterblich.",
    "options": [
      "uns",
      "sich",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2742765906"
    }
  },
  {
    "id": "vb-ref-t2-138",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sogar jetzt musste ich ____ kontaktieren.",
    "options": [
      "sich",
      "dich",
      "mich",
      "uns"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3698418842"
    }
  },
  {
    "id": "vb-ref-t2-139",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Leute verkleiden ____ als ihre Lieblingsfilmfigur.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2576703314"
    }
  },
  {
    "id": "vb-ref-t2-140",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir werden ____ netten Jazz anhören.",
    "options": [
      "euch",
      "sich",
      "mich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3141447663"
    }
  },
  {
    "id": "vb-ref-t2-141",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es waren so viele und Sie können ____ nur einmal hinrichten.",
    "options": [
      "uns",
      "sich",
      "mich",
      "dich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3845605987"
    }
  },
  {
    "id": "vb-ref-t2-142",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Der Mann hat ____ im Wald verlaufen.",
    "options": [
      "uns",
      "euch",
      "dich",
      "sich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3641155522"
    }
  },
  {
    "id": "vb-ref-t2-143",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John beschloss, ____ anstelle eines neuen Wagens einen Gebrauchtwagen zuzulegen.",
    "options": [
      "sich",
      "dich",
      "euch",
      "mich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:391703074"
    }
  },
  {
    "id": "vb-ref-t2-144",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich würde ____ gerne ringen sehen.",
    "options": [
      "dich",
      "uns",
      "mich",
      "euch"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:635148228"
    }
  },
  {
    "id": "vb-ref-t2-145",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie informierte ____ über ihre Abreise.",
    "options": [
      "mich",
      "dich",
      "euch",
      "sich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3142748389"
    }
  },
  {
    "id": "vb-ref-t2-146",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Es lohnt ____ nicht zu jammern.",
    "options": [
      "sich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3957951116"
    }
  },
  {
    "id": "vb-ref-t2-147",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich werde ____ nachmittags wiedersehen.",
    "options": [
      "sich",
      "uns",
      "dich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3197834802"
    }
  },
  {
    "id": "vb-ref-t2-148",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wenn wir nicht mitspielen, wird er ____ ganz sicher töten.",
    "options": [
      "sich",
      "uns",
      "mich",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3458414203"
    }
  },
  {
    "id": "vb-ref-t2-149",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wir gehen und lassen ____ etwas Privatsphäre.",
    "options": [
      "euch",
      "mich",
      "sich",
      "dich"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2590781012"
    }
  },
  {
    "id": "vb-ref-t2-150",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich befürchte, dass ich ____ dort langweile.",
    "options": [
      "uns",
      "dich",
      "sich",
      "mich"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3528572135"
    }
  },
  {
    "id": "vb-ref-t2-151",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "John weigerte ____, das Dokument zu unterzeichnen.",
    "options": [
      "sich",
      "euch",
      "mich",
      "uns"
    ],
    "answer": 0,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2193940605"
    }
  },
  {
    "id": "vb-ref-t2-152",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Deine Entschuldigungen sind für ____ wertlos.",
    "options": [
      "dich",
      "sich",
      "mich",
      "euch"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1867263132"
    }
  },
  {
    "id": "vb-ref-t2-153",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Englische Damen kleiden ____ abends genau wie alle anderen Damen.",
    "options": [
      "mich",
      "sich",
      "uns",
      "dich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:31874481"
    }
  },
  {
    "id": "vb-ref-t2-154",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Wenn es für ____ ist, zerreißen Sie es.",
    "options": [
      "euch",
      "mich",
      "dich",
      "sich"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:671368896"
    }
  },
  {
    "id": "vb-ref-t2-155",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Okay, schalten Sie ____ zurück auf Autopilot.",
    "options": [
      "euch",
      "dich",
      "sich",
      "uns"
    ],
    "answer": 3,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:3043737728"
    }
  },
  {
    "id": "vb-ref-t2-156",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Ich verstecke ____ inmitten einer Parade.",
    "options": [
      "uns",
      "dich",
      "mich",
      "sich"
    ],
    "answer": 2,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:1401411674"
    }
  },
  {
    "id": "vb-ref-t2-157",
    "engine": "mc",
    "prompt": "Choose the correct reflexive pronoun:",
    "stimulus": "Sie wollen ____ nicht teilnehmen lassen.",
    "options": [
      "uns",
      "mich",
      "sich",
      "euch"
    ],
    "answer": 1,
    "metadata": {
      "cefr": "B1",
      "system": "verb",
      "module": "reflexives",
      "tier": 2,
      "tags": [
        "grammar:reflexive",
        "mc"
      ],
      "groupId": "ref:2309966059"
    }
  }
];
