/* eslint-disable */
// Auto-generated by scripts/generate-content.ts — do not edit by hand.
import type { ExerciseItem } from "@/lib/content/schema";

export const reflexivesTier1: ExerciseItem[] = [
  {
    id: "vb-ref-t1-001",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ schuldig, weil ich gelogen habe.",
    options: ["mich", "euch", "uns", "dich"],
    answer: 0,
    translation: "I feel guilty because I have told a lie.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2506560896",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-002",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Können Sie ____ die Welt ohne Geld vorstellen?",
    options: ["euch", "uns", "sich", "mich"],
    answer: 2,
    translation: "Can you imagine the world without money?",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2822379448",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-003",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Darauf müssen wir ____ konzentrieren.",
    options: ["uns", "mich", "sich", "euch"],
    answer: 0,
    translation: "We must concentrate on that.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1032609500",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-004",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Der Mensch hat ____ seit der Steinzeit nicht allzu sehr verändert.",
    options: ["uns", "mich", "sich", "euch"],
    answer: 2,
    translation: "Humans haven't changed much since the Stone Age.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1006951743",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-005",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Dann werde ich ____ also verlassen.",
    options: ["euch", "dich", "uns", "sich"],
    answer: 1,
    translation: "Then, I'll be leaving you.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3213862073",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-006",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Die befinden ____ im Gang Nummer zwei.",
    options: ["sich", "dich", "uns", "mich"],
    answer: 0,
    translation: "They're in aisle number two.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2754838513",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-007",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Ich möchte ____ für unser letztes Zusammentreffen entschuldigen.",
    options: ["mich", "euch", "dich", "uns"],
    answer: 0,
    translation: "I'd like to apologize for our previous encounter.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1212639528",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-008",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Obwohl der Doktor sein Bestes gab, erholte ____ der Patient nur langsam.",
    options: ["mich", "sich", "euch", "uns"],
    answer: 1,
    translation:
      "Though the doctor did his best, the patient's recovery was slow.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:295281613",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-009",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Können wir ____ irgendwo unterhalten?",
    options: ["euch", "sich", "uns", "dich"],
    answer: 2,
    translation: "Is there somewhere we can talk?",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2953438933",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-010",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "John wird ____ nicht ändern.",
    options: ["euch", "dich", "uns", "sich"],
    answer: 3,
    translation: "John isn't going to change.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3424019554",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-011",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus:
      "Es ist fast unmöglich, ____ als Manga-Künstler seinen Lebensunterhalt zu verdienen.",
    options: ["mich", "dich", "sich", "uns"],
    answer: 2,
    translation: "Making a living as a manga artist is almost impossible.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3977620130",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-012",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Das Bild erinnert ____ an meine Studentenzeit.",
    options: ["uns", "sich", "mich", "euch"],
    answer: 2,
    translation: "This picture reminds me of when I was a student.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3502501885",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-013",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir müssen ____ um das Problem kümmern.",
    options: ["dich", "uns", "euch", "sich"],
    answer: 1,
    translation: "We must deal with this problem.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3253781890",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-014",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich fühle ____ tatsächlich etwas krank.",
    options: ["uns", "mich", "euch", "dich"],
    answer: 1,
    translation: "I'm feeling a little sick, actually.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1838483499",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-015",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Kannst du mir sagen, wo auf dieser Karte ich ____ befinde?",
    options: ["dich", "uns", "sich", "mich"],
    answer: 3,
    translation: "Can you tell me where I am on this map?",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1733325211",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-016",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Hoffentlich verirrst du ____ nicht.",
    options: ["dich", "euch", "mich", "uns"],
    answer: 0,
    translation: "I hope you won't get lost.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3599694057",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-017",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Er kann ____ nicht bewegen.",
    options: ["dich", "euch", "uns", "sich"],
    answer: 3,
    translation: "He can't move.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3349736674",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-018",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Aber es fühlt ____ so seltsam an.",
    options: ["sich", "euch", "dich", "mich"],
    answer: 0,
    translation: "But it just feels so strange.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3431344708",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-019",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir beraten Sie gerne und freuen ____ auf Sie.",
    options: ["euch", "dich", "uns", "sich"],
    answer: 2,
    translation:
      "We would be happy to advise you and look forward to hearing from you.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3004314009",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-020",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "John konnte ____ nicht vorstellen, jemanden zu erschießen.",
    options: ["sich", "mich", "uns", "euch"],
    answer: 0,
    translation: "John couldn't imagine himself shooting anyone.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1679711308",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-021",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie haben nur noch Stunden, um ____ zu entscheiden.",
    options: ["sich", "mich", "euch", "uns"],
    answer: 0,
    translation: "You only have 24 hours left to decide.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:265198870",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-022",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Gut, aber beeilen Sie ____.",
    options: ["mich", "euch", "uns", "sich"],
    answer: 3,
    translation: "Fine, but hurry.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1494740099",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-023",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ich kann nicht verstehen, worüber sie ____ beschweren sollte.",
    options: ["euch", "uns", "dich", "sich"],
    answer: 3,
    translation: "I can't understand what she has to complain about.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4275848007",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-024",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie können ____ im Flugzeug unterhalten.",
    options: ["dich", "sich", "euch", "uns"],
    answer: 1,
    translation: "You can talk on the plane.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:952916284",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-025",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Seine törichten Freunde wollen ____ morgen früh angreifen.",
    options: ["euch", "mich", "uns", "sich"],
    answer: 2,
    translation: "His foolish friends intend to attack us in the morning.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:1423279121",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-026",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie müssen ____ entspannen und einfach beruhigen.",
    options: ["sich", "uns", "euch", "mich"],
    answer: 0,
    translation: "You need to relax and just calm down.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:414097969",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-027",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Der Kapitän des Schiffes entschied ____ den Kurs zu ändern.",
    options: ["uns", "sich", "euch", "mich"],
    answer: 1,
    translation: "The captain of the ship decided to change course.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3711311194",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-028",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir bewegen ____ nach Norden.",
    options: ["mich", "euch", "dich", "uns"],
    answer: 3,
    translation: "We are heading north.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3019332818",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-029",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Meine Zunge fühlte ____ behaart an.",
    options: ["dich", "uns", "sich", "mich"],
    answer: 2,
    translation: "My tongue felt like it had hair on it.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4170640966",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-030",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wir sollten ____ jetzt drum kümmern.",
    options: ["mich", "euch", "uns", "dich"],
    answer: 2,
    translation: "We should worry about it now.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2231200701",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-031",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Sie erinnern ____ an einen entfernten Cousin.",
    options: ["dich", "sich", "mich", "uns"],
    answer: 2,
    translation: "You remind me of a distant cousin.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2855570100",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-032",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Unsere Gäste fühlen ____ bestens versorgt.",
    options: ["euch", "uns", "dich", "sich"],
    answer: 3,
    translation: "Our guests are very well looked after.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:3785478588",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-033",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Wisst ihr, wo wir ____ befinden?",
    options: ["sich", "euch", "dich", "uns"],
    answer: 3,
    translation: "Do you know where we are?",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:27181478",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-034",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Jetzt wird sie ____ bestimmt entspannen.",
    options: ["mich", "sich", "dich", "uns"],
    answer: 1,
    translation: "I'm sure she'll relax now.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2028350575",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-035",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "John kann ____ nicht konzentrieren.",
    options: ["sich", "mich", "euch", "dich"],
    answer: 0,
    translation: "John can't concentrate.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:4035519743",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
  {
    id: "vb-ref-t1-036",
    engine: "mc",
    prompt: "Choose the correct reflexive pronoun:",
    stimulus: "Ihr werdet ____ daran gewöhnen.",
    options: ["uns", "dich", "euch", "sich"],
    answer: 2,
    translation: "You will get used to it.",
    metadata: {
      cefr: "B1",
      system: "verb",
      module: "reflexives",
      tier: 1,
      tags: ["grammar:reflexive", "mc"],
      groupId: "ref:2072600844",
    },
    feedback: {
      correct:
        "That reflexive verb needs a pronoun matching its subject — you got it.",
      common: {
        "mc:wrong":
          "Reflexive pronouns must agree with the subject of the verb (ich → mich, du → dich, er/sie/es/wir/sie(pl) → sich/uns, ihr → euch).",
      },
    },
  },
];
