/**
 * scripts/generate-content-manifest.ts
 *
 * Emits content/manifest.generated.ts — a tiny, client-safe metadata file
 * (module titles/descriptions/counts + an id-prefix → module/tier map)
 * derived from the full content registry. Client components should import
 * from lib/content/manifest.ts (which re-exports this file) instead of
 * content/registry.ts, so the ~29MB of exercise item source never reaches
 * the browser bundle just to render a module list or a progress ring.
 *
 * Run with: npm run content:manifest
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CONTENT_MODULES } from "../content/registry";

interface ModuleMetaOut {
  id: string;
  slug: string;
  systemId: string;
  title: string;
  description: string;
  /** Shared id prefix for every item in this module, e.g. "vb-ref". */
  idPrefix: string;
  tierCounts: [number, number, number];
  totalCount: number;
}

function idPrefixFor(ids: string[]): string {
  // Ids look like "{prefix}-t{tier}-{seq}" — strip the trailing "-tN-seq".
  const sample = ids[0];
  if (!sample) return "";
  const m = sample.match(/^(.+)-t[123]-\d+$/);
  return m ? m[1]! : sample;
}

const meta: ModuleMetaOut[] = CONTENT_MODULES.map((m) => {
  const allIds = [...m.tiers[1], ...m.tiers[2], ...m.tiers[3]].map((i) => i.id);
  return {
    id: m.id,
    slug: m.slug,
    systemId: m.systemId,
    title: m.title,
    description: m.description,
    idPrefix: idPrefixFor(allIds),
    tierCounts: [m.tiers[1].length, m.tiers[2].length, m.tiers[3].length],
    totalCount: m.tiers[1].length + m.tiers[2].length + m.tiers[3].length,
  };
});

const body =
  `// Auto-generated by scripts/generate-content-manifest.ts — do not edit by hand.\n` +
  `// Client-safe metadata about content modules. Contains no exercise items.\n\n` +
  `export type ContentModuleMeta = {\n` +
  `  id: string;\n` +
  `  slug: string;\n` +
  `  systemId: string;\n` +
  `  title: string;\n` +
  `  description: string;\n` +
  `  idPrefix: string;\n` +
  `  tierCounts: [number, number, number];\n` +
  `  totalCount: number;\n` +
  `};\n\n` +
  `export const CONTENT_MODULE_META: ContentModuleMeta[] = ${JSON.stringify(meta, null, 2)};\n`;

writeFileSync(
  resolve(process.cwd(), "content", "manifest.generated.ts"),
  body,
  "utf8",
);
console.log(`content-manifest: wrote metadata for ${meta.length} modules.`);
