import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allExerciseItems, CONTENT_MODULES } from "../content/registry";

const outPath = join(process.cwd(), "content", "index.generated.ts");

const meta = {
  generatedAt: new Date().toISOString(),
  itemCount: allExerciseItems.length,
  moduleCount: CONTENT_MODULES.length,
  itemIds: allExerciseItems.map((i) => i.id),
  moduleSlugs: CONTENT_MODULES.map((m) => m.slug),
};

const body = `/* eslint-disable */
// Auto-generated by scripts/index-content.ts — do not edit by hand.
export const CONTENT_INDEX = ${JSON.stringify(meta, null, 2)} as const;
`;

writeFileSync(outPath, body, "utf8");
console.log(`Wrote ${outPath} (${meta.itemCount} items, ${meta.moduleCount} modules).`);
